api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json:
            - application/json
            - application/merge-patch+json
    formats:
        json:
            mime_types:
                - application/json
        jsonld:
            mime_types:
                - application/ld+json
        html:
            mime_types:
                - text/html
    swagger:
        versions: [3]
